-- MySQL Script generated by MySQL Workbench
-- Mon May 21 03:49:16 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SARA-BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SARA-BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SARA-BD` DEFAULT CHARACTER SET utf8 ;
USE `SARA-BD` ;

-- -----------------------------------------------------
-- Table `SARA-BD`.`Flotilla`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SARA-BD`.`Flotilla` (
  `matriculaFlotilla` VARCHAR(10) NOT NULL,
  `calleDireccion` VARCHAR(45) NOT NULL,
  `coloniaDireccion` VARCHAR(45) NOT NULL,
  `numeroDireccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  `codigoPostal` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`matriculaFlotilla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SARA-BD`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SARA-BD`.`Usuario` (
  `rfc` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `municipio` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `calleDireccion` VARCHAR(60) NOT NULL,
  `colDireccion` VARCHAR(60) NOT NULL,
  `numDireccion` INT(4) NOT NULL,
  `codigoPostal` VARCHAR(5) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `contrasena` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`rfc`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SARA-BD`.`Vehiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SARA-BD`.`Vehiculo` (
  `noMotor` VARCHAR(25) NOT NULL,
  `climatizado` ENUM('si', 'no') NOT NULL,
  `transmision` ENUM('manual', 'auto') NOT NULL,
  `numPasajeros` INT NOT NULL,
  `numPuertas` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `version` VARCHAR(45) NOT NULL,
  `kilometraje` DOUBLE NOT NULL,
  `kml` DOUBLE NOT NULL,
  `gps` ENUM('si', 'no') NOT NULL,
  `descripcion` TEXT NOT NULL,
  `estado` ENUM('1', '2', '3', '4') NOT NULL,
  `disponibilidad` ENUM('disponible', 'nodisponible') NOT NULL,
  `Flotilla_matriculaFlotilla` VARCHAR(10) NOT NULL,
  `precioDia` DOUBLE NOT NULL,
  `Thumbnail` TEXT NOT NULL,
  `Cliente_rfc` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`noMotor`),
  INDEX `fk_Vehiculo_Flotilla1_idx` (`Flotilla_matriculaFlotilla` ASC),
  INDEX `fk_Vehiculo_Cliente1_idx` (`Cliente_rfc` ASC),
  CONSTRAINT `fk_Vehiculo_Flotilla1`
    FOREIGN KEY (`Flotilla_matriculaFlotilla`)
    REFERENCES `SARA-BD`.`Flotilla` (`matriculaFlotilla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vehiculo_Cliente1`
    FOREIGN KEY (`Cliente_rfc`)
    REFERENCES `SARA-BD`.`Usuario` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SARA-BD`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SARA-BD`.`Administrador` (
  `matricula` VARCHAR(13) NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contrasena` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`matricula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SARA-BD`.`TarjetaCredito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SARA-BD`.`TarjetaCredito` (
  `idTarjetaCredito` VARCHAR(5) NOT NULL,
  `numeroTarjeta` INT(16) NOT NULL,
  `cuatroDigitos` VARCHAR(45) NOT NULL,
  `mesCaducidad` INT(2) NOT NULL,
  `anoCaducidad` INT(2) NOT NULL,
  `ccv` INT(3) NOT NULL,
  `nombreTarjeta` VARCHAR(70) NOT NULL,
  `Usuario_rfc` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idTarjetaCredito`),
  INDEX `fk_TarjetaCredito_Usuario1_idx` (`Usuario_rfc` ASC),
  CONSTRAINT `fk_TarjetaCredito_Usuario1`
    FOREIGN KEY (`Usuario_rfc`)
    REFERENCES `SARA-BD`.`Usuario` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SARA-BD`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SARA-BD`.`Factura` (
  `numeroFactura` INT(9) NOT NULL,
  `fechaFacturacion` DATE NOT NULL,
  `concepto` TEXT NOT NULL,
  `totalImpuestosAñadidos` DOUBLE NOT NULL,
  `direccionAlmacenamiento` TEXT NOT NULL,
  `diasRenta` INT NOT NULL,
  `Vehiculo_noMotor` VARCHAR(25) NOT NULL,
  `Usuario_rfc` VARCHAR(13) NOT NULL,
  `lugarEntrega` TEXT NOT NULL,
  PRIMARY KEY (`numeroFactura`, `Vehiculo_noMotor`, `Usuario_rfc`),
  INDEX `fk_Factura_Vehiculo1_idx` (`Vehiculo_noMotor` ASC),
  INDEX `fk_Factura_Usuario1_idx` (`Usuario_rfc` ASC),
  CONSTRAINT `fk_Factura_Vehiculo1`
    FOREIGN KEY (`Vehiculo_noMotor`)
    REFERENCES `SARA-BD`.`Vehiculo` (`noMotor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Usuario1`
    FOREIGN KEY (`Usuario_rfc`)
    REFERENCES `SARA-BD`.`Usuario` (`rfc`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
